name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Create empty keystore
      run: echo "storeFile=/" > keystore.properties
    - name: KTLint
      run: ./gradlew ktlint
    - name: Unit Tests
      run: ./gradlew testFullDebugUnitTest
#     - name: Android Instrumantation Tests
#       run: ./gradlew connectedFullDebugAndroidTest
    - name: Build with Gradle
      run: ./gradlew buildFullDebug
